# Shared titles to avoid (to prevent duplication across different engines)

PUBLISHED_TITLES = [
    # Historical/Classic Cases
    "The Dyatlov Pass Incident (REAL STORY)",
    "The Mary Celeste",
    "The Tamam Shud Case",
    "The Dyatlov Pass Incident",
    "The Dyatlov Pass",
    "The Roanoke Colony (UNSOLVED)",
    "The Roanoke Colony (REAL STORY)",
    "The Roanoke Colony-TRUE-STORY",
    "The Roanoke Colony",
    "The Hinterkaifeck Murders (TRUE STORY)",
    "The Hinterkaifeck Murders (SHOCKING)",
    "The Hinterkaifeck Murders (UNSOLVED)",
    "The Hinterkaifeck Murders",
    "The Isdal Woman (MYSTERY)",
    "The Isdal Woman (REAL STORY)",
    "The Isdal Woman-TRUE-STORY",
    "The Isdal Woman",
    "The Disappearance of Flight 19 (SHOCKING)",
    "The Disappearance of Flight 19-TRUE-STORY",
    "The Disappearance of Flight 19",
    # Christmas/Holiday Stories
    "The Sodder Children (Christmas Horror)",
    "Christmas Eve Shadow",
    "Christmas Eve Vanishing",
    "Christmas Eve Scream",
    "Christmas Eve Disappearance (MYSTERY)",
    "Christmas Eve Disappearance (REAL STORY)",
    "Christmas Eve Disappearance (TRUE STORY)",
    "Christmas Eve Disappearance (UNSOLVED)",
    "The Christmas Eve Abduction at Smiley's Inn (REAL STORY)",
    "Frozen Christmas Eve (MYSTERY)",
    "Christmas Eve Terror (UNSOLVED)",
    # New Year Stories
    "New Year's Dark Freeze (UNSOLVED)",
    "New Year's Chill (UNSOLVED)",
    "New Year's Frozen Scream (MYSTERY)",
    # Other Cases
    "The Vanishing Hitchhiker",
    "The Vanishing Hotel",
    # Old Psychology Content (keep to avoid)
    "Your Reality is a Lie",
    "The 6-Second Window of Total Control",
    "Unlock the Forbidden Art of Hypnotic Storytelling",
    "The 7 Seconds That Control Your Reality",
    "The Shadow Play Technique: Unmasking the Dark Side of Influence",
    "The Hidden Power of Priming: How to Control Minds with Unconscious Cues",
    "The 'Lost Hours Effect': How Your Brain Tricks You into Obedience",
    "The 4-Second Mind-Control Trick: Unleash the Power of Micro-Messages",
    "The 7 Hidden Secrets to Hypnotic Influence You Won't Believe",
    "Dark Psychology Trick to Read Minds Instantly \ud83e\udde0 #shorts",
    "The Dark Art of Mind Reading | Dark Psychology Facts",
    "1% of Your Brain? The Truth About Mental Potential",
    "The Mysterious Fast Radio Bursts (FRBs)",
    "The World's Fastest Computer Memory is a Dot?",
    "You Won't Believe This Alien World",
    "You Won't Believe This AI Secret!",
    "YOU WON'T BELIEVE THIS SPACE SECRET!"
]
